#!/usr/bin/env bash
# gen-inventory.sh — Generate ansible/inventory/hosts.ini from Terraform output.
#
# This script reads the Elastic IP from Terraform state and writes a minimal
# Ansible inventory file. Running this after terraform apply keeps the inventory
# in sync with the provisioned instance — no manual copy-paste required.
#
# The generated hosts.ini is gitignored. Regenerate it whenever the instance
# is recreated (terraform destroy + apply changes the EIP allocation).
#
# Usage:
#   ./scripts/gen-inventory.sh
#   make inventory

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/environments/dev"
INVENTORY_FILE="${REPO_ROOT}/ansible/inventory/hosts.ini"

echo "Reading EIP address from Terraform output..."

EIP=$(terraform -chdir="${TF_DIR}" output -raw eip_address 2>/dev/null) || {
  echo "ERROR: Failed to read eip_address from Terraform output." >&2
  echo "       Run 'make tf-apply' first to provision the instance." >&2
  exit 1
}

if [[ -z "${EIP}" ]]; then
  echo "ERROR: eip_address is empty. Is the infrastructure deployed?" >&2
  exit 1
fi

mkdir -p "${REPO_ROOT}/ansible/inventory"

cat > "${INVENTORY_FILE}" << EOF
# Generated by scripts/gen-inventory.sh — do not edit manually.
# Regenerate with: make inventory

[vpn]
wireguard-server ansible_host=${EIP}
EOF

echo "Wrote ${INVENTORY_FILE}"
echo "  wireguard-server ansible_host=${EIP}"
